name: lemmy-help

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: emmylua to vimdoc
    steps:
      - uses: actions/checkout@v2

      - name: Generating help
        run: |
          curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./.github/scripts/gen_doc.sh

      - name: Updating Usage in README
        run: |
          ./.github/scripts/update_readme.sh

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(docs): auto-generate vimdoc & update usage"
          file_pattern: 'doc/*.txt README.md'
